/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;


import java.awt.Color;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class Calculadora extends javax.swing.JFrame {
    
    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");


    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        txtOperacion = new javax.swing.JLabel();
        btn_borrarOperacion = new javax.swing.JButton();
        btn_cambioColor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_pot = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_par1 = new javax.swing.JButton();
        btn_pro = new javax.swing.JButton();
        btn_rest = new javax.swing.JButton();
        btn_sum = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_masmenos = new javax.swing.JButton();
        btn_dec = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_div1 = new javax.swing.JButton();
        btn_raiz = new javax.swing.JButton();
        btn_par2 = new javax.swing.JButton();
        btn_borrar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(59, 66, 75));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtResultado.setText("0");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 310, 41));

        txtOperacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(59, 66, 75));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 310, 29));

        btn_borrarOperacion.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_borrarOperacion.setForeground(new java.awt.Color(59, 66, 75));
        btn_borrarOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierda.png"))); // NOI18N
        btn_borrarOperacion.setText("←");
        btn_borrarOperacion.setFocusPainted(false);
        btn_borrarOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrarOperacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierda.png"))); // NOI18N
        btn_borrarOperacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierdaPress.png"))); // NOI18N
        btn_borrarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_borrarOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 50, 30));

        btn_cambioColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDoff.png"))); // NOI18N
        btn_cambioColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambioColorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cambioColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pot.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_pot.setForeground(new java.awt.Color(59, 66, 75));
        btn_pot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_pot.setText("^");
        btn_pot.setFocusPainted(false);
        btn_pot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pot.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_pot.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 50));

        btn_ce.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_ce.setForeground(new java.awt.Color(59, 66, 75));
        btn_ce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_ce.setText("CE");
        btn_ce.setFocusPainted(false);
        btn_ce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ce.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_ce.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        btn_c.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_c.setForeground(new java.awt.Color(59, 66, 75));
        btn_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_c.setText("C");
        btn_c.setFocusPainted(false);
        btn_c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_c.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });
        jPanel2.add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 50, 50));

        btn_par1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_par1.setForeground(new java.awt.Color(59, 66, 75));
        btn_par1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_par1.setText("(");
        btn_par1.setFocusPainted(false);
        btn_par1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_par1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_par1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_par1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_par1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_par1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        btn_pro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_pro.setForeground(new java.awt.Color(59, 66, 75));
        btn_pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_pro.setText("x");
        btn_pro.setFocusPainted(false);
        btn_pro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_pro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 50));

        btn_rest.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_rest.setForeground(new java.awt.Color(59, 66, 75));
        btn_rest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_rest.setText("-");
        btn_rest.setFocusPainted(false);
        btn_rest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_rest.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_rest.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 50, 50));

        btn_sum.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sum.setForeground(new java.awt.Color(59, 66, 75));
        btn_sum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_sum.setText("+");
        btn_sum.setFocusPainted(false);
        btn_sum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sum.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_sum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 50, 50));

        btn_igual.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton3.png"))); // NOI18N
        btn_igual.setText("=");
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, 50));

        btn_7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(59, 66, 75));
        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_7.setText("7");
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, 50));

        btn_8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(59, 66, 75));
        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_8.setText("8");
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, 50));

        btn_9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(59, 66, 75));
        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_9.setText("9");
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 50, 50));

        btn_4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(59, 66, 75));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_4.setText("4");
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 50));

        btn_5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(59, 66, 75));
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_5.setText("5");
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 50, 50));

        btn_6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(59, 66, 75));
        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_6.setText("6");
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 50, 50));

        btn_1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(59, 66, 75));
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_1.setText("1");
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 50));

        btn_2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(59, 66, 75));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_2.setText("2");
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 50, 50));

        btn_3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(59, 66, 75));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_3.setText("3");
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 50, 50));

        btn_masmenos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btn_masmenos.setForeground(new java.awt.Color(59, 66, 75));
        btn_masmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_masmenos.setText("+/-");
        btn_masmenos.setFocusPainted(false);
        btn_masmenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_masmenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_masmenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_masmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masmenosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_masmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 50));

        btn_dec.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_dec.setForeground(new java.awt.Color(59, 66, 75));
        btn_dec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_dec.setText(".");
        btn_dec.setFocusPainted(false);
        btn_dec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dec.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_dec.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 50, 50));

        btn_0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(59, 66, 75));
        btn_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.png"))); // NOI18N
        btn_0.setText("0");
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 50, 50));

        btn_div1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_div1.setForeground(new java.awt.Color(59, 66, 75));
        btn_div1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_div1.setText("/");
        btn_div1.setFocusPainted(false);
        btn_div1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_div1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_div1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_div1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_div1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_div1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 50));

        btn_raiz.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_raiz.setForeground(new java.awt.Color(59, 66, 75));
        btn_raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonRaiz.png"))); // NOI18N
        btn_raiz.setFocusPainted(false);
        btn_raiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_raiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonRaiz.png"))); // NOI18N
        btn_raiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonRaizPress.png"))); // NOI18N
        btn_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raizActionPerformed(evt);
            }
        });
        jPanel2.add(btn_raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        btn_par2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_par2.setForeground(new java.awt.Color(59, 66, 75));
        btn_par2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_par2.setText(")");
        btn_par2.setFocusPainted(false);
        btn_par2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_par2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_par2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_par2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_par2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_par2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        btn_borrar4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_borrar4.setForeground(new java.awt.Color(59, 66, 75));
        btn_borrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_borrar4.setText("←");
        btn_borrar4.setFocusPainted(false);
        btn_borrar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrar4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.png"))); // NOI18N
        btn_borrar4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png"))); // NOI18N
        btn_borrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrar4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_borrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potActionPerformed
        error();
        float num1=0,num2=0,r=0;
        int band=0;
        String re;
       
        
        if(txtResultado.getText().equals("Indefinido")){
            txtResultado.setText("0");
        }
        else{
            for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
             
                if(txtResultado.getText().substring(i-1,i).equals("^") || txtResultado.getText().substring(i).equals("^") ){
                    
                    band = 1;
                    break;
                } 
            } 
        } 
        if (band==0){
            if (txtResultado.getText()!= "")
                añadirNumeroResultado("^");
        }
            
        for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
                if(txtResultado.getText().substring(i-1,i).equals("^")){
                   
                    band = 1;
             
                    num1 = Float.parseFloat(txtResultado.getText().substring(0, i-1));
                    
                    num2 = Float.parseFloat(txtResultado.getText().substring(i));
                    int ka = 0;
                    for (int j=0;j<txtResultado.getText().length();j++){
                        if (j>=1){
                            if(txtResultado.getText().substring(j-1,j).equals(".")){
                            if(txtResultado.getText().substring(j,j+1).equals("5")){
                                ka = 1;
                                break;
                            }
                            }
                        }
                        
                    }
                    
                    if(ka == 1){
                        txtResultado.setText("Indefinido");
                        break;
                    }
                    r = (float) Math.pow(num1, num2);
                    
                    re = Float.toString(r);
                    
                    txtResultado.setText(re);
                    
                    for ( i=0;i<txtResultado.getText().length();i++){
                if (i >= 1){
                    if(txtResultado.getText().substring(i-1, i).equals(".")){
                        band = 0;
                        for (int j=i+1;j<=txtResultado.getText().length();j++){
                            if(txtResultado.getText().substring(j-1, j).equals("0")){
                                band = 0;
                            }
                            else{
                                band = 1;
                                break;
                            }
                        }
                        if(band == 1){
                            txtResultado.setText("");
                            txtResultado.setText(re);
                        }
                        else{
                            txtOperacion.setText(txtResultado.getText().substring(0,i-1));
                            txtResultado.setText(txtResultado.getText().substring(0,i-1));
                        }
                        break;
                    }
                }       
            }
                    añadirNumero("=");
                    break;
                } 
            } 
        }
        }
         
        
    }//GEN-LAST:event_btn_potActionPerformed

    private void btn_restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restActionPerformed
        error();
        pasar();
        int bandera = 0;
        for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(i).equals("-") || txtOperacion.getText().substring(i).equals("*") || txtOperacion.getText().substring(i).equals("+") || txtOperacion.getText().substring(i).equals("/")){
                    bandera = 1;
                    break;
                } 
            } 
        } 
        if(bandera == 0){
            if(txtOperacion.getText() != "")
                añadirNumero("-");
        }
    }//GEN-LAST:event_btn_restActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
        
        txtResultado.setText("0");
    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumActionPerformed
        error();
        pasar();
        int bandera = 0;
        for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(i).equals("-") || txtOperacion.getText().substring(i).equals("*") || txtOperacion.getText().substring(i).equals("+") || txtOperacion.getText().substring(i).equals("/")){
                    bandera = 1;
                    break;
                } 
            } 
        } 
        if(bandera == 0){
            if(txtOperacion.getText() != "")
                añadirNumero("+");
        }
    }//GEN-LAST:event_btn_sumActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        try {
            int ka = 0;
            if (txtResultado.getText().equals("Indefinido")){
                txtResultado.setText("");
            }
            
            if(txtResultado.getText().equals("")){
                
            }
            else{
               int bandera = 0;
            float num1,num2,r;
            String re;
            for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
                if(txtResultado.getText().substring(i-1,i).equals("^")){
           
                    num1 = Float.parseFloat(txtResultado.getText().substring(0, i-1));
                    num2 = Float.parseFloat(txtResultado.getText().substring(i));
                    
                    
                    for (int j=0;j<txtResultado.getText().length();j++){
                        if (j>=1){
                            if(txtResultado.getText().substring(j-1,j).equals(".")){
                            if(txtResultado.getText().substring(j,j+1).equals("5")){
                                ka = 1;
                                break;
                            }
                            }
                        }
                        
                    }
                    
                    if(ka == 1){
                        txtResultado.setText("");
                        txtResultado.setText("Indefinido");
                        
                        break;
                    }
                    else{
                        r = (float) Math.pow(num1, num2);
                   
                    re = Float.toString(r);
                    txtOperacion.setText("");
                    txtResultado.setText(re);
                    bandera = 1;
                    for ( i=0;i<txtResultado.getText().length();i++){
                if (i >= 1){
                    if(txtResultado.getText().substring(i-1, i).equals(".")){
                        int band = 0;
                        for (int j=i+1;j<=txtResultado.getText().length();j++){
                            if(txtResultado.getText().substring(j-1, j).equals("0")){
                                band = 0;
                            }
                            else{
                                band = 1;
                                break;
                            }
                        }
                        if(band == 1){
                            txtResultado.setText("");
                            txtResultado.setText(re);
                        }
                        else{
                            txtOperacion.setText(txtResultado.getText().substring(0,i-1));
                            txtResultado.setText(txtResultado.getText().substring(0,i-1));
                        }
                        break;
                    }
                }       
            }
                    }
                    
                    
            añadirNumero("=");
                    break;
                } 
            } 
        } 
            
        if(ka != 1){
            if (bandera == 0){
            
            int bande = 0;
            for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(i).equals("-") || txtOperacion.getText().substring(i).equals("*") || txtOperacion.getText().substring(i).equals("+") || txtOperacion.getText().substring(i).equals("/")){
                    bande = 1;
                    break;
                    } 
                } 
            } 
            
            
            if(bande==0){
                txtOperacion.setText(txtResultado.getText());
                añadirNumero("=");
            } 
            else{
            
            if (txtResultado.getText().equals("0")){
                txtOperacion.setText("");
                txtResultado.setText("Indefinido");
            }
            else{
                añadirNumero(txtResultado.getText());
            String resultado = se.eval(txtOperacion.getText()).toString();
            txtResultado.setText(resultado);
            for (int i=0;i<txtResultado.getText().length();i++){
                if (i >= 1){
                    if(txtResultado.getText().substring(i-1, i).equals(".")){
                        int band = 0;
                        for (int j=i+1;j<=txtResultado.getText().length();j++){
                            if(txtResultado.getText().substring(j-1, j).equals("0")){
                                band = 0;
                            }
                            else{
                                band = 1;
                                break;
                            }
                        }
                        if(band == 1){
                            txtResultado.setText("");
                            txtResultado.setText(resultado);
                        }
                        else{
                            
                            txtResultado.setText(txtResultado.getText().substring(0,i-1));
                        }
                        break;
                    }
                }       
            }
            añadirNumero("=");
            }
            
        }   
            }
        }    
        
              
            }
        } catch (Exception e) {
            btn_c.doClick();
            txtResultado.setText("Error");
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("7");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("7");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("7"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("7");  
            } 
        }
            
        }
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("8");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("8");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("8"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("8");  
            } 
        }
            
        }
        
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("9");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("9");
        }
        else{
            
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("9"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("9");  
            } 
        }
            
        }
        
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("4");
        }
        else{
            if (bande != 1){
            añadirNumeroResultado("4");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("4"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("4");  
            } 
        }
            
        }
        
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("5");
        }
        else{
            if (bande != 1){
            añadirNumeroResultado("5");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("5"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("5");  
            } 
        }
            
        }
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("6");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("6");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("6"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("6");  
            } 
        }
            
        }
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("1");
        }
        else{
            
            if (bande != 1){
                añadirNumeroResultado("1");
            
            
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                
                txtOperacion.setText("");
                añadirNumeroResultado("1"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("1");  
            } 
        }
            
        }
        
        
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        error();
        int bande = igualFinal();
        
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("2");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("2");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("2"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("2");  
            } 
        }
            
        }
        
        
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        error();
        int bande = igualFinal();
       
        if (txtResultado.getText().equals("0")){
                txtResultado.setText("");
                añadirNumeroResultado("3");
        }
        else{
            
            if (bande != 1){
            añadirNumeroResultado("3");
        }
        else{
            int band = encontrarPotencia();
            if(band == 1){
                txtOperacion.setText("");
                añadirNumeroResultado("3"); 
            }
            else{
              txtOperacion.setText("");
            txtResultado.setText("");
            añadirNumeroResultado("3");  
            } 
        }
            
        }
        
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_masmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masmenosActionPerformed
        error();
        String num = txtResultado.getText();
        
        if(txtResultado.getText().equals("")){
            
        }
        else if(txtResultado.getText().substring(0,1).equals("-")){
            txtResultado.setText(txtResultado.getText().substring(1,txtResultado.getText().length()));
        }
        else{
                txtResultado.setText("-" + num);
       
        }
        //añadirNumeroResultado("0");
        
        //btn_igual.doClick();
    }//GEN-LAST:event_btn_masmenosActionPerformed

    private void btn_decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decActionPerformed
        error();
        int bandera = 0;
        
        for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
 System.out.println("es:"+txtResultado.getText().substring(i));
                if(txtResultado.getText().substring(i-1,i).equals(".") || txtResultado.getText().substring(i).equals(".")){
                    
                    bandera = 1;
                    break;
                } 
            } 
        } 
        if(bandera == 0){
            if(txtResultado.getText() != "")
                añadirNumeroResultado(".");
        }
        
        
    }//GEN-LAST:event_btn_decActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        
        txtOperacion.setText("");
        txtResultado.setText("0");
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_par1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_par1ActionPerformed
        error();
        pasar();
        añadirNumero("(");
        
    }//GEN-LAST:event_btn_par1ActionPerformed

    private void btn_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proActionPerformed
        error();
        pasar();
        int bandera = 0;
        for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(i).equals("-") || txtOperacion.getText().substring(i).equals("*") || txtOperacion.getText().substring(i).equals("+") || txtOperacion.getText().substring(i).equals("/")){
                    bandera = 1;
                    break;
                } 
            } 
        } 
        if(bandera == 0){
            if(txtOperacion.getText() != "")
                añadirNumero("*");
        }
        
        
    }//GEN-LAST:event_btn_proActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        
        error();
        int bande = igualFinal();
        int bandera = 0 ;
        if (txtResultado.getText().equals("")){
            añadirNumeroResultado("0");
        }
        else{
            if (bande != 1){
            bandera = cero();
            System.out.println("entro : "+ bandera);
            System.out.println("entro es : "+ txtResultado.getText().substring(0,1));
            if (bandera!=1){
                System.out.println("1entro : 1");
                if (txtResultado.getText().substring(0,1).equals("0")){
                    
                }
                else{
                    añadirNumeroResultado("0");
                }
                
            }
            else{
                if (txtResultado.getText().substring(0,1).equals("0")){
                    
                }
                else{
                    añadirNumeroResultado("0");
                }
            }
            
            
        }
        else{
            int band = encontrarPotencia();
            System.out.println("entro");
            if(band == 1){
                
                bandera = cero();
                if (bandera == 1){
                    txtOperacion.setText("");
                    añadirNumeroResultado("0");
                }
                 
            }
            else{
                System.out.println("2entro : "+ bandera);
            System.out.println("2entro es : "+ txtResultado.getText().substring(0));
                if (bandera == 1){
                    txtOperacion.setText("");
                    txtResultado.setText("");
                    añadirNumeroResultado("0");
                }
                
            } 
        }
        }
        
        
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_div1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_div1ActionPerformed
        // TODO add your handling code here:
        error();
        pasar();
        int bandera = 0;
        for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(i).equals("-") || txtOperacion.getText().substring(i).equals("*") || txtOperacion.getText().substring(i).equals("+") || txtOperacion.getText().substring(i).equals("/")){
                    bandera = 1;
                    break;
                } 
            } 
        } 
        if(bandera == 0){
            if(txtOperacion.getText() != "")
                añadirNumero("/");
        }
    }//GEN-LAST:event_btn_div1ActionPerformed

    private void btn_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raizActionPerformed
        // TODO add your handling code here:
        error();
        float num1=0,r=0;
        int band=0,bandera=0;
        String re;
        
        
        
        if(txtResultado.getText().equals("") || txtResultado.getText().equals("Indefinido")){
            txtResultado.setText("0");
            
        }
        
        
        
        else{
            
            if(txtResultado.getText().substring(0, 1).equals("-")){
            txtOperacion.setText("");
            txtResultado.setText("Indefinido");
            }
            else{
                for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){

                if(txtResultado.getText().substring(i-1,i).equals("^")){

                    bandera = 1;
                    break;
                } 
            } 
        } 
        if (bandera==0){
            num1 = Float.parseFloat(txtResultado.getText());
            r = (float) Math.pow(num1, 0.5);
 
            re = Float.toString(r);
            txtOperacion.setText("");
            txtResultado.setText(re);
            
            int i;
                    for ( i=0;i<txtResultado.getText().length();i++){
                if (i >= 1){
                    if(txtResultado.getText().substring(i-1, i).equals(".")){
                        band = 0;
                        for (int j=i+1;j<=txtResultado.getText().length();j++){
                            if(txtResultado.getText().substring(j-1, j).equals("0")){
                                band = 0;
                            }
                            else{
                                band = 1;
                                break;
                            }
                        }
                        if(band == 1){
                            txtOperacion.setText(re);
                            txtResultado.setText("");
                            txtResultado.setText(re);
                        }
                        else{
                            txtOperacion.setText(txtResultado.getText().substring(0,i-1));
                            txtResultado.setText(txtResultado.getText().substring(0,i-1));
                        }
                        break;
                    }
                }       
            }
            añadirNumero("=");
                   
        } 
            }
            
           
        }   
        
        
           
    }//GEN-LAST:event_btn_raizActionPerformed

    private void btn_par2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_par2ActionPerformed
        error();
        pasar();
        añadirNumero(")");      // TODO add your handling code here:
    }//GEN-LAST:event_btn_par2ActionPerformed

    private void btn_borrarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarOperacionActionPerformed
        // TODO add your handling code here:
        if(txtOperacion.getText().equals("")){
            
        }
        else{
           String texto = txtOperacion.getText().substring(0, txtOperacion.getText().length()-1);
           txtOperacion.setText(texto); 
           
        }
        
    }//GEN-LAST:event_btn_borrarOperacionActionPerformed

    private void btn_borrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrar4ActionPerformed
        // TODO add your handling code here:
        if(txtResultado.getText().equals("")){
            txtResultado.setText("0");
        }
        else{
           String texto = txtResultado.getText().substring(0, txtResultado.getText().length()-1);
           txtResultado.setText(texto); 
           if(txtResultado.getText().equals("")){
            txtResultado.setText("0");
        }
        }
        
    }//GEN-LAST:event_btn_borrar4ActionPerformed
    
    boolean modoOscuro = false;
            
    private void btn_cambioColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambioColorActionPerformed
        // TODO add your handling code here:
        
        if(modoOscuro == false){
            
        jPanel1.setBackground(Color.decode("#212b41"));
        jPanel2.setBackground(Color.decode("#2e3951"));
        txtOperacion.setForeground(Color.decode("#ffffff"));
        txtResultado.setForeground(Color.decode("#ffffff"));
        
        cambiarColor2(btn_par1);
        cambiarColor2(btn_par2);
        cambiarColor2(btn_c);
        cambiarColor2(btn_ce);
        cambiarColor2(btn_borrar4);
        
        cambiarColor2(btn_pot);
        cambiarColor2(btn_div1);
        cambiarColor2(btn_pro);
        cambiarColor2(btn_rest);
        cambiarColor2(btn_sum);
        
        btn_cambioColor.setIcon(new ImageIcon(getClass().getResource("/imagenes/MDon.png")));
        
        btn_igual.setIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDigual.png")));
        btn_igual.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDigual.png")));
        btn_igual.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDigualPress.png")));
        btn_igual.setForeground(Color.decode("#ffffff"));
        
        btn_raiz.setIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDraiz.png")));
        btn_raiz.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDraiz.png")));
        btn_raiz.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/BotonMDraizPress.png")));
        btn_raiz.setForeground(Color.decode("#ffffff"));
        
        btn_borrarOperacion.setIcon(new ImageIcon(getClass().getResource("/imagenes/BotonborrarMD.png")));
        btn_borrarOperacion.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/BotonborrarMD.png")));
        btn_borrarOperacion.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/BotonborrarMDPress.png")));
        btn_borrarOperacion.setForeground(Color.decode("#ffffff"));
        
        cambiarColor(btn_1);
        cambiarColor(btn_2);
        cambiarColor(btn_3);
        cambiarColor(btn_4);
        cambiarColor(btn_5);
        cambiarColor(btn_6);
        cambiarColor(btn_7);
        cambiarColor(btn_8);
        cambiarColor(btn_9);
        cambiarColor(btn_0);
        cambiarColor(btn_masmenos);
        cambiarColor(btn_dec);
        modoOscuro = true;    
        }
        else{
            jPanel1.setBackground(Color.decode("#f4fdfb"));
        jPanel2.setBackground(Color.decode("#ffffff"));
        txtOperacion.setForeground(Color.decode("#000000"));
        txtResultado.setForeground(Color.decode("#000000"));
        
        
        btn_cambioColor.setIcon(new ImageIcon(getClass().getResource("/imagenes/MDoff.png")));
        
        
        
        
        cambiarColor4(btn_par1);
        cambiarColor4(btn_par2);
        cambiarColor4(btn_c);
        cambiarColor4(btn_ce);
        cambiarColor4(btn_borrar4);
        
        cambiarColor4(btn_pot);
        cambiarColor4(btn_div1);
        cambiarColor4(btn_pro);
        cambiarColor4(btn_rest);
        cambiarColor4(btn_sum);
        
        btn_igual.setIcon(new ImageIcon(getClass().getResource("/imagenes/Boton3.png")));
        btn_igual.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1.png")));
        btn_igual.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png")));
        btn_igual.setForeground(Color.decode("#ffffff"));
        
        btn_raiz.setIcon(new ImageIcon(getClass().getResource("/imagenes/BotonRaiz.png")));
        btn_raiz.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/BotonRaiz.png")));
        btn_raiz.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/BotonRaizPress.png")));
        btn_raiz.setForeground(Color.decode("#ffffff"));
        
        btn_borrarOperacion.setIcon(new ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierda.png")));
        btn_borrarOperacion.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierda.png")));
        btn_borrarOperacion.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/fondoFlechaIzquierdaPress.png")));
        btn_borrarOperacion.setForeground(Color.decode("#000000"));
        
        cambiarColor3(btn_1);
        cambiarColor3(btn_2);
        cambiarColor3(btn_3);
        cambiarColor3(btn_4);
        cambiarColor3(btn_5);
        cambiarColor3(btn_6);
        cambiarColor3(btn_7);
        cambiarColor3(btn_8);
        cambiarColor3(btn_9);
        cambiarColor3(btn_0);
        cambiarColor3(btn_masmenos);
        cambiarColor3(btn_dec);
        modoOscuro = false;
        }
        
    }//GEN-LAST:event_btn_cambioColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    public void cambiarColor(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1MD.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1MD.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1MDPress.png")));
        btn.setForeground(Color.decode("#ffffff"));
    }
    
    public void cambiarColor2(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1MDPress.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1MDPress.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Boton2MDPress.png")));
        btn.setForeground(Color.decode("#ffffff"));
    }
    
    public void cambiarColor3(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imagenes/Boton2.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png")));
        btn.setForeground(Color.decode("#000000"));
    }
    
    public void cambiarColor4(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Boton1_Presionado.png")));
        btn.setForeground(Color.decode("#000000"));
    }
    
    public void añadirNumero(String digito){
        txtOperacion.setText(txtOperacion.getText() + digito);
    }
    
    public void añadirNumeroResultado(String digito){
        txtResultado.setText(txtResultado.getText() + digito);
    }
    
    public void error(){
        if(txtResultado.getText().equals("Error")){
            btn_c.doClick();
        }
    }
    
    public int cero(){
        int band = 0;
        if (txtResultado.getText().equals("0")){
            band = 1;
            
        }
        else{
            for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
             
                if(txtResultado.getText().substring(i-1,i).equals("0") || txtResultado.getText().substring(i).equals("0") ){
                    
                    band = 1;
                    break;
                } 
            } 
        }
        }
        
        
        return band;
    }
    
    public int encontrarPotencia(){
        int band = 0;
            for (int i=0;i<txtResultado.getText().length();i++){
            if(i >= 1){
             
                if(txtResultado.getText().substring(i-1,i).equals("^") || txtResultado.getText().substring(i).equals("^") ){
                    
                    band = 1;
                    break;
                    } 
                } 
            } 
            return band;
    }
    
    public int igualFinal(){
        int bande = 0;
            for (int i=0;i<txtOperacion.getText().length();i++){
            if(i >= 1){
            //System.out.println("es:"+txtOperacion.getText().substring(i-1,i));
                if(txtOperacion.getText().substring(txtOperacion.getText().length()-1).equals("=")){
                    bande = 1;
                    break;
                    } 
                } 
            } 
        return bande;
    }
    
    public void pasar(){
        String k = txtResultado.getText();
        if (txtResultado.getText() != ""){
            
            txtOperacion.setText(txtOperacion.getText() + txtResultado.getText());
            txtResultado.setText("");
        }
        
        
        for (int i=0;i<txtOperacion.getText().length();i++){
            //if (i==4)
                //System.out.println("letra:"+txtOperacion.getText().substring(i-1,i));
            if (i >= 1){
                if(txtOperacion.getText().substring(i-1,i).equals("=")){
                    txtOperacion.setText(k);
                    break;
                }
            }
            
        }
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_borrar4;
    private javax.swing.JButton btn_borrarOperacion;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_cambioColor;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_dec;
    private javax.swing.JButton btn_div1;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_masmenos;
    private javax.swing.JButton btn_par1;
    private javax.swing.JButton btn_par2;
    private javax.swing.JButton btn_pot;
    private javax.swing.JButton btn_pro;
    private javax.swing.JButton btn_raiz;
    private javax.swing.JButton btn_rest;
    private javax.swing.JButton btn_sum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
